// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customerservice.proto

/*
Package customerservice is a generated protocol buffer package.

It is generated from these files:
	customerservice.proto

It has these top-level messages:
	CustomerRequest
	Customer
	Address
*/
package customerservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CustomerRequest struct {
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
}

func (m *CustomerRequest) Reset()                    { *m = CustomerRequest{} }
func (m *CustomerRequest) String() string            { return proto.CompactTextString(m) }
func (*CustomerRequest) ProtoMessage()               {}
func (*CustomerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CustomerRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

type Customer struct {
	CustomerId string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	GivenName  string   `protobuf:"bytes,2,opt,name=given_name,json=givenName" json:"given_name,omitempty"`
	Surname    string   `protobuf:"bytes,3,opt,name=surname" json:"surname,omitempty"`
	Address    *Address `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *Customer) Reset()                    { *m = Customer{} }
func (m *Customer) String() string            { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()               {}
func (*Customer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Customer) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Customer) GetGivenName() string {
	if m != nil {
		return m.GivenName
	}
	return ""
}

func (m *Customer) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *Customer) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	Line1 string `protobuf:"bytes,1,opt,name=line1" json:"line1,omitempty"`
	Line2 string `protobuf:"bytes,2,opt,name=line2" json:"line2,omitempty"`
	City  string `protobuf:"bytes,3,opt,name=city" json:"city,omitempty"`
	State string `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Zip   string `protobuf:"bytes,5,opt,name=zip" json:"zip,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Address) GetLine1() string {
	if m != nil {
		return m.Line1
	}
	return ""
}

func (m *Address) GetLine2() string {
	if m != nil {
		return m.Line2
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomerRequest)(nil), "customerservice.CustomerRequest")
	proto.RegisterType((*Customer)(nil), "customerservice.Customer")
	proto.RegisterType((*Address)(nil), "customerservice.Address")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Customers service

type CustomersClient interface {
	GetCustomerDetails(ctx context.Context, opts ...grpc.CallOption) (Customers_GetCustomerDetailsClient, error)
}

type customersClient struct {
	cc *grpc.ClientConn
}

func NewCustomersClient(cc *grpc.ClientConn) CustomersClient {
	return &customersClient{cc}
}

func (c *customersClient) GetCustomerDetails(ctx context.Context, opts ...grpc.CallOption) (Customers_GetCustomerDetailsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Customers_serviceDesc.Streams[0], c.cc, "/customerservice.Customers/get_customer_details", opts...)
	if err != nil {
		return nil, err
	}
	x := &customersGetCustomerDetailsClient{stream}
	return x, nil
}

type Customers_GetCustomerDetailsClient interface {
	Send(*CustomerRequest) error
	Recv() (*Customer, error)
	grpc.ClientStream
}

type customersGetCustomerDetailsClient struct {
	grpc.ClientStream
}

func (x *customersGetCustomerDetailsClient) Send(m *CustomerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *customersGetCustomerDetailsClient) Recv() (*Customer, error) {
	m := new(Customer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Customers service

type CustomersServer interface {
	GetCustomerDetails(Customers_GetCustomerDetailsServer) error
}

func RegisterCustomersServer(s *grpc.Server, srv CustomersServer) {
	s.RegisterService(&_Customers_serviceDesc, srv)
}

func _Customers_GetCustomerDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CustomersServer).GetCustomerDetails(&customersGetCustomerDetailsServer{stream})
}

type Customers_GetCustomerDetailsServer interface {
	Send(*Customer) error
	Recv() (*CustomerRequest, error)
	grpc.ServerStream
}

type customersGetCustomerDetailsServer struct {
	grpc.ServerStream
}

func (x *customersGetCustomerDetailsServer) Send(m *Customer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *customersGetCustomerDetailsServer) Recv() (*CustomerRequest, error) {
	m := new(CustomerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Customers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customerservice.Customers",
	HandlerType: (*CustomersServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "get_customer_details",
			Handler:       _Customers_GetCustomerDetails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "customerservice.proto",
}

func init() { proto.RegisterFile("customerservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x65, 0xda, 0x12, 0x72, 0x1d, 0x8a, 0x4e, 0x45, 0x32, 0x48, 0x88, 0x28, 0x53, 0xa6,
	0x0a, 0xc2, 0x2f, 0x40, 0x4c, 0x2c, 0x0c, 0x59, 0x18, 0x23, 0x13, 0x9f, 0x2a, 0x4b, 0x4d, 0xd2,
	0xfa, 0x9c, 0x4a, 0xf0, 0x4b, 0xf8, 0xb9, 0xa8, 0x8e, 0xcd, 0x10, 0x84, 0xd8, 0xee, 0x7d, 0xef,
	0x59, 0x7e, 0x3e, 0xc3, 0x55, 0x33, 0xb0, 0xeb, 0x5b, 0xb2, 0x4c, 0xf6, 0x68, 0x1a, 0xda, 0xec,
	0x6d, 0xef, 0x7a, 0x5c, 0x4d, 0x70, 0x5e, 0xc2, 0xea, 0x39, 0xa0, 0x8a, 0x0e, 0x03, 0xb1, 0xc3,
	0x3b, 0x58, 0xc6, 0x54, 0x6d, 0xb4, 0x14, 0x99, 0x28, 0xd2, 0x0a, 0x22, 0x7a, 0xd1, 0xf9, 0x97,
	0x80, 0x8b, 0x78, 0xe8, 0xdf, 0x34, 0xde, 0x02, 0x6c, 0xcd, 0x91, 0xba, 0xba, 0x53, 0x2d, 0xc9,
	0x33, 0xef, 0xa7, 0x9e, 0xbc, 0xaa, 0x96, 0x50, 0x42, 0xc2, 0x83, 0xf5, 0xde, 0xcc, 0x7b, 0x51,
	0x62, 0x09, 0x89, 0xd2, 0xda, 0x12, 0xb3, 0x9c, 0x67, 0xa2, 0x58, 0x96, 0x72, 0x33, 0x7d, 0xd4,
	0xd3, 0xe8, 0x57, 0x31, 0x98, 0x1f, 0x20, 0x09, 0x0c, 0xd7, 0xb0, 0xd8, 0x99, 0x8e, 0x1e, 0x42,
	0xa5, 0x51, 0x44, 0x5a, 0x86, 0x22, 0xa3, 0x40, 0x84, 0x79, 0x63, 0xdc, 0x47, 0x68, 0xe0, 0xe7,
	0x53, 0x92, 0x9d, 0x72, 0xe4, 0x2f, 0x4f, 0xab, 0x51, 0xe0, 0x25, 0xcc, 0x3e, 0xcd, 0x5e, 0x2e,
	0x3c, 0x3b, 0x8d, 0xa5, 0x86, 0x34, 0x2e, 0x83, 0xf1, 0x0d, 0xd6, 0x5b, 0x72, 0xf5, 0xcf, 0x46,
	0x34, 0x39, 0x65, 0x76, 0x8c, 0xd9, 0xaf, 0xea, 0x93, 0xad, 0xdf, 0x5c, 0xff, 0x99, 0x28, 0xc4,
	0xbd, 0x78, 0x3f, 0xf7, 0xff, 0xf7, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x76, 0xff, 0x00, 0x30,
	0xd8, 0x01, 0x00, 0x00,
}
